---

- name: Install required packages
  apt: name=openssl state=installed

- name: Base CA paths created
  file:
    path: "/root/{{ item[0] }}/{{ item[1] }}"
    state: directory
  with_nested:
    - [ 'ca', 'ca/intermediate' ]
    - [ 'certs', 'crl', 'newcerts' ]

- name: Private CA path created
  file:
    path: /root/{{ item }}/private
    state: directory
    mode: 0700
  with_items:
    - [ 'ca', 'ca/intermediate' ]

- name: Index files created
  copy: src=index dest=/root/{{ item }}/index force=no
  with_items:
    - [ 'ca', 'ca/intermediate' ]

- name: Serial files created
  copy: content=1000 dest=/root/{{ item }}/serial force=no
  with_items:
    - [ 'ca', 'ca/intermediate' ]

- name: Root CA openssl configuration set
  template: src=openssl_root_ca.cnf.j2 dest=/root/ca/openssl.cnf force=no

- package: name=python-openssl state=present

- name: CA private key created
  openssl_privatekey:
    path: /root/ca/private/ca.key.pem

