---

- name: Install required packages
  apt: name=openssl state=installed

- name: Base CA paths created
  file:
    path: "/root/{{ item[0] }}/{{ item[1] }}"
    state: directory
  with_nested:
    - [ 'ca', 'ca/intermediate' ]
    - [ 'certs', 'crl', 'csr', 'newcerts' ]

- name: Private CA path created
  file:
    path: /root/{{ item }}/private
    state: directory
    mode: 0700
  with_items:
    - [ 'ca', 'ca/intermediate' ]

- name: Index files created
  copy: src=index.txt dest=/root/{{ item }}/index.txt force=no
  with_items:
    - [ 'ca', 'ca/intermediate' ]

- name: Serial files created
  copy: content=1000 dest=/root/{{ item }}/serial force=no
  with_items:
    - [ 'ca', 'ca/intermediate' ]

- name: Root CA openssl configuration set
  template: src=openssl_root_ca.cnf.j2 dest=/root/ca/openssl.cnf

- name: Root CA private key created
  command: openssl genrsa -aes256 -passout pass:secret -out private/ca.key.pem 4096
  args:
    chdir: /root/ca
    creates: private/ca.key.pem

- file: path=/root/ca/private/ca.key.pem mode=0400

- name: Create root CA cert
  command: openssl req -config openssl.cnf -key private/ca.key.pem -passin pass:secret -new -x509 -days 7300 -sha256 -subj "/O=Miguelaco's Home/CN=Miguelaco Root CA" -extensions v3_ca -out certs/ca.cert.pem
  args:
    chdir: /root/ca
    creates: certs/ca.cert.pem

- name: Check root CA cert
  command: openssl x509 -noout -in certs/ca.cert.pem
  args:
    chdir: /root/ca

- name: Intermediate CA openssl configuration set
  template: src=openssl_intermediate_ca.cnf.j2 dest=/root/ca/intermediate/openssl.cnf

- name: Intermediate CA private key created
  command: openssl genrsa -aes256 -passout pass:secret -out intermediate/private/intermediate.key.pem 4096
  args:
    chdir: /root/ca
    creates: intermediate/private/intermediate.key.pem

- file: path=/root/ca/intermediate/private/intermediate.key.pem mode=0400

- name: Create intermediate CSR
  command: openssl req -config intermediate/openssl.cnf -key intermediate/private/intermediate.key.pem -passin pass:secret -new -sha256 -subj "/O=Miguelaco's Home/CN=Miguelaco Intermediate CA" -extensions v3_ca -out intermediate/csr/intermediate.csr.pem
  args:
    chdir: /root/ca
    creates: intermediate/csr/intermediate.csr.pem

- name: Sign intermediate CSR
  command: openssl ca -config openssl.cnf -extensions v3_intermediate_ca -days 3650 -passin pass:secret -notext -batch -md sha256 -in intermediate/csr/intermediate.csr.pem -out intermediate/certs/intermediate.cert.pem
  args:
    chdir: /root/ca
    creates: intermediate/certs/intermediate.cert.pem

#- name: Check intermediate CA cert
#  command: openssl x509 -noout -in certs/ca.cert.pem
#  args:
#    chdir: /root/ca
