Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.define "kdc" do |machine|
        machine.vm.hostname = "kdc.miguelaco.com"
        machine.vm.network "private_network", ip: "192.168.77.10"
    end
    config.vm.define "kclient" do |machine|
        machine.vm.hostname = "kclient.miguelaco.com"
        machine.vm.network "private_network", ip: "192.168.77.20"
    end
#    config.vm.provision :shell, inline: "echo 'Provisioning pki'"
#    config.vm.provision :ansible do |ansible|
#        ansible.verbose = "v"
#        ansible.inventory_path = "provisioning/inventory"
#        ansible.playbook = "kdc.yml"
#    end
end
