Vagrant.configure("2") do |config|
    config.vm.define :test1 do |test1|
        test1.vm.provision :shell, inline: "echo 'Provisioning test1'"
        test1.vm.box = "debian/jessie64"
        test1.vm.hostname = "test1"
    end
    config.vm.define :test2 do |test2|
        test2.vm.provision :shell, inline: "echo 'Provisioning test2'"
        test2.vm.box = "debian/jessie64"
        test2.vm.hostname = "test2"
    end
end
