Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "server" do |machine|
    machine.vm.hostname = "server"
  end
  config.vm.define "client" do |machine|
    machine.vm.hostname = "client"
  end
end
