---

- name: Waiting for bootstrap healthy state
  wait_for:
    host: 192.168.65.10
    port: 8080
    delay: 5
    timeout: 10

- name: Download dcos_install.sh
  get_url:
    url=http://192.168.65.10:8080/dcos_install.sh
    dest=/home/vagrant/dcos_install.sh

- name: Install dcos
  shell: >
    bash dcos_install.sh "{{ node_type }}" &&
    touch .skip
  args:
    chdir: /home/vagrant
    creates: .skip
