---

- name: Waiting for bootstrap healthy state
  wait_for:
    host: "{{ hostvars['boot'].detected_ipv4 }}"
    port: 8080
    timeout: 30

- name: Download dcos_install.sh
  get_url:
    url=http://{{ hostvars['boot'].detected_ipv4 }}:8080/dcos_install.sh
    dest=/home/vagrant/dcos_install.sh

- name: Install dcos
  shell: >
    bash dcos_install.sh "{{ node_type }}" &&
    touch .skip
  args:
    chdir: /home/vagrant
    creates: .skip
