---

- name: Download dcos_generate_config.sh
  get_url:
    url=https://downloads.dcos.io/dcos/stable/1.12.0/dcos_generate_config.sh
    dest=/home/vagrant/dcos_generate_config.sh
    checksum=sha256:d40cf41b3d56d85774669cde5d497038eb461165be9e4ae8368c801e7b0a021f

- name: Create genconf dir
  file: path=/home/vagrant/genconf state=directory

- name: Copy ip-detect script to genconf dir
  copy:
    src: /usr/local/bin/ip-detect
    dest: /home/vagrant/genconf/ip-detect
    remote_src: yes

- name: Create config.yaml
  copy:
    dest: /home/vagrant/genconf/config.yaml
    content: |
      ---
      bootstrap_url: http://{{ hostvars['boot'].advertise_addr }}:8080
      cluster_name: {{ cluster_name }}
      exhibitor_storage_backend: static
      master_discovery: static
      master_list:
      {% for host in groups['masters'] %}
      - {{ hostvars[host]['advertise_addr'] }}
      {% endfor %}
      resolvers:
      {% for host in dns_resolvers %}
      - {{ host }}
      {% endfor %}
      ssh_port: 22
      ssh_user: vagrant

- name: Generate DC/OS config
  shell: bash dcos_generate_config.sh && touch .skip
  args:
    chdir: /home/vagrant
    creates: .skip

- name: Install prerequisites for docker module
  yum: name=docker-python state=latest

- name: Running nginx docker
  docker_container:
    name: nginx-bootstrap
    image: nginx
    ports:
      - "{{ hostvars['boot'].advertise_addr }}:8080:80"
    volumes:
      - /home/vagrant/genconf/serve:/usr/share/nginx/html