---

- name: Download dcos_generate_config.sh
  get_url:
    url=https://downloads.dcos.io/dcos/stable/1.11.0/commit/b6d6ad4722600877fde2860122f870031d109da3/dcos_generate_config.sh
    dest=/home/vagrant/dcos_generate_config.sh
    checksum=sha256:f42800c773a79c8fa4b5ae837626805ac67420d388433bbc9891520b17668ba9

- name: Create genconf dir
  file: path=/home/vagrant/genconf state=directory

- name: Copy ip-detect script to genconf dir
  copy:
    src: /usr/local/bin/ip-detect
    dest: /home/vagrant/genconf/ip-detect
    remote_src: yes

- name: Create config.yaml
  copy:
    dest: /home/vagrant/genconf/config.yaml
    content: |
      ---
      bootstrap_url: http://{{ hostvars['boot'].advertise_addr }}:8080
      cluster_name: {{ cluster_name }}
      exhibitor_storage_backend: static
      master_discovery: static
      master_list:
      {% for host in groups['masters'] %}
      - {{ hostvars[host]['advertise_addr'] }}
      {% endfor %}
      resolvers:
      {% for host in dns_resolvers %}
      - {{ host }}
      {% endfor %}
      ssh_port: 22
      ssh_user: vagrant

- name: Generate DC/OS config
  shell: bash dcos_generate_config.sh && touch .skip
  args:
    chdir: /home/vagrant
    creates: .skip

- name: Install prerequisites for docker module
  yum: name={{ item }} state=latest
  with_items:
    - docker-python

- name: Running nginx docker
  docker_container:
    name: nginx-bootstrap
    image: nginx
    ports:
      - "{{ hostvars['boot'].advertise_addr }}:8080:80"
    volumes:
      - /home/vagrant/genconf/serve:/usr/share/nginx/html