---

- name: Bootstrap ACL system
  uri:
    url: http://127.0.0.1:8500/v1/acl/bootstrap
    method: PUT
    status_code: 200, 403
  register: root_token
  no_log: no
  run_once: true

- name: Save consul root_token
  local_action:
    copy
      content={{ root_token.json.ID }}
      dest={{ consul_init_dir }}/root_token
  become: no
  run_once: yes
  when: root_token.status == 200 and root_token.json

- name: Lookup root_token file
  set_fact:
    consul_root_token: "{{ lookup('file', '{{ consul_init_dir }}/root_token') }}"
  no_log: not debug | default(true)

- name: Create agent ACL
  uri:
    url: http://127.0.0.1:8500/v1/acl/create
    method: PUT
    headers:
      X-Consul-Token: "{{ consul_root_token }}"
    body_format: json
    body:
      Name: acl_agent_token
      Type: client
      Rules: "node \"\" { policy = \"write\" } service \"\" { policy = \"read\" }"
  register: acl_agent_token_response
  no_log: not debug | default(true)
  when: acl_agent_token is undefined
  run_once: true

- name: Update agent ACL
  uri:
    url: http://127.0.0.1:8500/v1/acl/update
    method: PUT
    headers:
      X-Consul-Token: "{{ consul_root_token }}"
    body_format: json
    body:
      Id: "{{ acl_agent_token }}"
      Name: acl_agent_token
      Type: client
      Rules: "node \"\" { policy = \"write\" } service \"\" { policy = \"read\" }"
  no_log: not debug | default(true)
  when: acl_agent_token is defined
  run_once: true

- name: Save acl_agent_token
  local_action:
    copy
      content={{ acl_agent_token_response.json.ID }}
      dest={{ consul_init_dir }}/acl_agent_token
  become: no
  run_once: yes
  when: acl_agent_token is undefined

- name: Lookup acl_agent_token file
  set_fact:
    acl_agent_token: "{{ lookup('file', '{{ consul_init_dir }}/acl_agent_token') }}"
  no_log: not debug | default(true)
  when: acl_agent_token is undefined

- name: Copy consul config file
  template:
    src=consul.json.j2
    dest={{ consul_config_file }}
    owner=consul
    group=consul
    mode=0600
  when: acl_agent_token_response is not skipped
  notify:
    - Start consul service

- name: Anonymous ACL
  uri:
    url: http://127.0.0.1:8500/v1/acl/update
    method: PUT
    headers:
      X-Consul-Token: "{{ consul_root_token }}"
    body_format: json
    body:
      Id: anonymous
      Name: Anonymous Token
      Type: client
      Rules: "node \"\" { policy = \"read\" } service \"\" { policy = \"read\" }"
  run_once: true
