---

- name: Set consul as resolver
  import_tasks: dnsmasq.yml

- name: Create consul group
  group: name=consul system=yes

- name: Create consul user
  user:
    name=consul
    group=consul
    system=yes

- name: Create consul home dir
  file:
    path={{ item }}
    state=directory
  with_items:
    - "{{ consul_home }}"
    - "{{ consul_home }}/bin"
    - "{{ consul_config_dir }}"

- name: Create consul data dir
  file:
    path={{ item }}
    state=directory
    owner=consul
    group=consul
    mode=0755
  with_items:
    - "{{ consul_data_dir }}"

- name: Create consul init directory
  local_action: file path={{ consul_init_dir }} state=directory
  become: no
  run_once: yes

- name: Check consul package
  local_action:
    stat
      path={{ role_path }}/files/consul_{{ consul_version }}_linux_amd64.zip
  become: no
  run_once: yes
  register: consul_package

- name: Download consul package locally
  local_action:
    get_url
      url=https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
      dest={{ role_path }}/files
      force=no
  become: no
  run_once: yes
  when: not consul_package.stat.exists

- package: name=unzip state=present

- name: Copy consul package to hosts
  unarchive:
    src={{ role_path }}/files/consul_{{ consul_version }}_linux_amd64.zip
    dest={{ consul_home }}/bin
  notify:
    - Start consul service
    - Wait for consul leader election

- name: Check current config file
  stat: path={{ consul_config_file }}
  register: current_conf_file
  run_once: yes
  become: no

- name: Get current config file
  slurp:
    src: "{{ consul_config_file }}"
  register: current_conf_b64
  run_once: yes
  when: current_conf_file.stat.exists

- name: Set current_conf fact
  set_fact:
    current_conf: "{{ current_conf_b64.content | b64decode }}"
  run_once: yes
  when: current_conf_b64.content is defined

- name: Set consul_encrypt fact from current_conf
  set_fact:
    consul_encrypt: "{{ current_conf.encrypt }}"
  run_once: yes
  when: current_conf is defined

- name: Set consul_root_token fact from current_conf
  set_fact:
    consul_root_token: "{{ current_conf.acl.tokens.master }}"
  run_once: yes
  when: current_conf is defined and current_conf.acl.tokens is defined

- name: Set consul_agent_token fact from current_conf
  set_fact:
    consul_agent_token: "{{ current_conf.acl.tokens.agent }}"
  run_once: yes
  when: current_conf is defined and current_conf.acl.tokens is defined

- name: Generate encryption key
  command: "{{ consul_home }}/bin/consul keygen"
  register: keygen
  run_once: yes
  when: consul_encrypt is undefined

- name: Set consul_encrypt fact
  set_fact:
    consul_encrypt: "{{ keygen.stdout }}"
  run_once: yes
  when: consul_encrypt is undefined

- name: Check cert serial number file
  local_action: stat path={{ consul_init_dir }}/cert_serial_number
  register: consul_cert_serial_number_result
  run_once: yes
  become: no

- name: Lookup cert serial number file
  set_fact:
    consul_cert_serial_number: "{{ lookup('file', '{{ consul_init_dir }}/cert_serial_number') }}"
  no_log: not debug | default(true)
  when: consul_cert_serial_number_result.stat.exists

- name: Copy consul config file
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner=consul
    group=consul
    mode={{ item.mode }}
  with_items:
    - { src: "consul.json.j2", dest: "{{ consul_config_file }}", mode: "0600" }
    - { src: "consul.systemd.j2", dest: "/etc/systemd/system/consul.service", mode: "0644" }
  notify:
    - Start consul service
    - Wait for consul leader election

- name: Set consul env variables
  template:
    src=templates/consul.sh.j2
    dest=/etc/profile.d/consul.sh
    owner=consul
    group=consul

- meta: flush_handlers

- name: Setup ACLs
  import_tasks: acl.yml

- meta: flush_handlers
