---

- stat: path={{ consul_secrets_dir }}/server.cert.crt
  register: server_cert_result

- block:
  - name: Generate private key
    openssl_privatekey:
      path: "{{ consul_secrets_dir }}/server.key.crt"

  - name: Generate certificate signing request
    openssl_csr:
      path: "/tmp/server.csr"
      privatekey_path: "{{ consul_secrets_dir }}/server.key.crt"
      common_name: "{{ consul_service_consul }}"
      subject_alt_name: "DNS:{{ node_consul }}, DNS:{{ node_consul_long }}, DNS:server.{{ consul_datacenter }}.{{ consul_domain }}"

  - name: Generate self signed certificate
    openssl_certificate:
      path: "{{ consul_secrets_dir }}/server.cert.crt"
      privatekey_path: "{{ consul_secrets_dir }}/server.key.crt"
      csr_path: "{{ consul_secrets_dir }}/server.csr"
      provider: selfsigned
    notify:
      - Start consul service

  when: not server_cert_result.stat.exists