---

vault_version: 0.11.4
vault_home: /opt/eos/vault
vault_config_file: "{{ vault_home }}/conf/vault.hcl"

consul_node_name: "{{ inventory_hostname_short }}"
consul_domain: consul
consul_datacenter: dc1
node_consul: "{{ inventory_hostname_short }}.node.{{ consul_domain }}"
consul_service_consul: consul.service.{{ consul_domain }}
vault_service_consul: vault.service.{{ consul_domain }}
vault_init_dir: "{{ playbook_dir }}/.vault_init"
consul_init_dir: "{{ playbook_dir }}/.consul_init"
