---

- block:
  - name: Install required packages
    package: name={{ item }} state=present
    with_items:
      - NetworkManager
      - dnsmasq
    notify:
      - Disable dnsmasq service
      - Start NetworkManager service

  - name: Configure NetworkManager to use dnsmasq
    copy:
      content: |
        [main]
        dns=dnsmasq
      dest: /etc/NetworkManager/conf.d/dnsmasq.conf
    notify:
      - Disable dnsmasq service
      - Start NetworkManager service

  - name: Setup consul as resolver for 'consul' domain
    copy:
      content: |
        # Enable forward lookup of the 'consul' domain:
        server=/consul/127.0.0.1#8600
      dest: /etc/NetworkManager/dnsmasq.d/10-consul
    notify:
      - Disable dnsmasq service
      - Start NetworkManager service

- always:
  - meta: flush_handlers