Vagrant.configure("2") do |config|
    config.vm.box = "debian/jessie64"
    config.vm.hostname = "pki"
#    config.vm.provision :shell, inline: "echo 'Provisioning pki'"
    config.vm.provision :ansible do |ansible|
        ansible.verbose = "v"
#        ansible.inventory_path = "provisioning/inventory"
        ansible.playbook = "pki.yml"
    end
end
