---
- hosts: all
  become: yes
  vars:
    role_name: role2

  tasks:
  - package: name={{ item }} state=present
    with_items:
      - docker
      - bind-utils

  - systemd:
      name: docker
      state: started
      enabled: yes
      daemon-reload: yes

  - name: Log into DockerHub
    docker_login:
      username: eosstratio
      password: 30s_t34m