Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.hostname = "dockerhost"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "main.yml"
    ansible.verbose = true
    ansible.compatibility_mode = "2.0"
  end
end
