Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.hostname = "dockerhost"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "main.yml"
    ansible.verbose = true
  end
end