---

- hosts: all
  roles:
    - { role: common, tags: [ 'common', 'always' ] }
    - { role: docker, tags: [ 'docker', 'always' ] }
    - { role: dcos-cli, tags: [ 'dcos', dcos-cli' ] }

- hosts: kms
  roles:
    - { role: kms, tags: [ 'kms' ] }

- hosts: bootstrap
  roles:
    - { role: dcos-setup, tags: [ 'dcos', 'dcos-setup' ] }

- hosts: masters
  strategy: free
  roles:
    - { role: dcos-install, tags: [ 'dcos', 'dcos-install', 'masters' ] }

- hosts: agents
  strategy: free
  roles:
    - { role: dcos-install, tags: [ 'dcos', 'dcos-install', 'agents' ] }
