---

- name: Disable dnsmasq service
  systemd:
    name: dnsmasq
    state: stopped
    enabled: no
    masked: yes

- name: Start NetworkManager service
  systemd:
    name: NetworkManager
    state: restarted

- name: Start consul service
  systemd:
    name: consul
    state: restarted
    enabled: yes
    daemon-reload: yes
