Vagrant.configure("2") do |config|
  N = 2
  (1..N).each do |machine_id|
    config.vm.box = "debian/jessie64"
    config.vm.define "test#{machine_id}" do |machine|
      machine.vm.hostname = "test#{machine_id}"
      machine.vm.network "private_network", ip: "192.168.77.#{20+machine_id}"

      # Only execute once the Ansible provisioner,
      # when all the machines are up and ready.
      if machine_id == N
        machine.vm.provision :ansible do |ansible|
          # Disable default limit to connect to all the machines
          ansible.limit = "all"
          ansible.playbook = "consul.yml"
          ansible.verbose = true
        end
      end
    end
  end
end
