Vagrant.configure("2") do |config|
  N = 2
  (1..N).each do |machine_id|
    config.vm.box = "centos/7"
    config.vm.define "sd#{machine_id}" do |machine|
      machine.vm.hostname = "sd#{machine_id}"
      machine.vm.network "private_network", ip: "192.168.77.#{20+machine_id}"

      # Only execute once the Ansible provisioner,
      # when all the machines are up and ready.
      if machine_id == N
        machine.vm.provision :ansible do |ansible|
          # Disable default limit to connect to all the machines
          ansible.limit = "all"
          ansible.compatibility_mode = "2.0"
          ansible.playbook = "consul.yml"
          ansible.verbose = true
          #ansible.tags = [ "consul" ]
        end
      end
    end
  end
end
