---

- name: Download consul package locally
  local_action:
    get_url
      url=https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
      dest=consul/files
      force=no
  become: no

- package: name=unzip state=installed

- name: Copy consul package to hosts
  unarchive:
    src=files/consul_{{ consul_version }}_linux_amd64.zip
    dest=/opt/consul/bin

- name: Create consul group
  group:
    name=consul
    system=yes

- name: Create consul user
  user:
    name=consul
    group=consul
    system=yes

- name: Create consul directory
  file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
    mode: 0755
  
  with_items:
    - "{{ consul_home }}"
    - "{{ consul_home }}/bin"
    - "{{ consul_home }}/cert"
    - "{{ consul_home }}/data"
    - "{{ consul_config_dir }}"

- name: Touch the log file
  file:
    state=touch
    path={{ consul_log_dir }}/consul
    owner=consul
    group=consul

- name: Copy consul config file
  template:
    src=templates/consul.json.j2
    dest={{ consul_config_file }}
    owner=consul
    group=consul
    mode=0755
  notify:
    - Start consul service

- name: Copy consul systemd script
  template:
    src=templates/consul.systemd.j2
    dest=/etc/systemd/system/consul.service
    owner=root
    group=root
    mode=0644
  notify:
    - Start consul service
