---

consul_version: 1.4.0
consul_home: /opt/eos/consul
consul_data_dir: /var/consul
consul_config_dir: "{{ consul_home }}/conf"
consul_config_file: "{{ consul_config_dir }}/consul.json"
consul_secrets_dir: "{{ consul_config_dir }}/secrets"
consul_reset_tls: no

consul_node_name: "{{ inventory_hostname_short }}"
consul_domain: consul
consul_datacenter: dc1
node_consul: "{{ inventory_hostname_short }}.node.{{ consul_domain }}"
node_consul_long: "{{ inventory_hostname_short }}.node.{{ consul_datacenter }}.{{ consul_domain }}"
consul_service_consul: consul.service.{{ consul_domain }}
vault_service_consul: vault.service.{{ consul_domain }}
vault_init_dir: "{{ playbook_dir }}/.vault_init"
consul_init_dir: "{{ playbook_dir }}/.consul_init"
