---

consul_version: 1.1.0
consul_home: /usr/local
consul_data_dir: /var/consul
consul_config_dir: /etc/consul.d
consul_config_file: /etc/consul.json
consul_init_dir: "{{ playbook_dir }}/.consul_init"
consul_node_name: "{{ inventory_hostname_short }}"
consul_domain: consul
consul_datacenter: dc1
node_consul: "{{ inventory_hostname_short }}.node.{{ consul_domain }}"
consul_service_consul: consul.service.{{ consul_domain }}
