Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "kdc" do |machine|
    machine.vm.hostname = "kdc"
    machine.vm.network "private_network", ip: "192.168.77.10"
  end
  config.vm.define "kclient" do |machine|
    machine.vm.hostname = "kclient"
    machine.vm.network "private_network", ip: "192.168.77.20"
  end
end
