Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.define "bootstrap" do |machine|
    machine.vm.hostname = "bootstrap"
    machine.vm.network "private_network", ip: "192.168.77.10"
  end
  config.vm.define "node" do |machine|
    machine.vm.hostname = "node"
    machine.vm.network "private_network", ip: "192.168.77.11"
  end
end
