---

- name: Ensure vault is started
  systemd:
    name: vault
    state: started

- name: Check vault init status
  uri:
    url: https://{{ inventory_hostname }}.node.consul:8200/v1/sys/init
    validate_certs: no
    status_code: 200, 429, 500, 501, 503
  register: init_status
  until: result.status == 200 and result.json
  run_once: true

- block:
  - name: Init vault
    uri:
      url: https://{{ inventory_hostname }}.node.consul:8200/v1/sys/init
      method: PUT
      validate_certs: no
      body_format: json
      body:
        secret_shares: 5
        secret_threshold: 3
    register: init_response
    no_log: yes
    run_once: true

  - name: Save vault init data
    local_action:
      copy
        content={{ init_response.json }}
        dest=vault_init_data
    become: no
    run_once: yes
  when: not init_status.json.initialized

- name: Check vault sealed status
  uri:
    url: https://{{ inventory_hostname }}.node.consul:8200/v1/sys/seal-status
    validate_certs: no
  register: seal_status

- name: Lookup vault init data
  set_fact:
    vault_init_data: "{{ lookup('file', 'vault_init_data') }}"
  no_log: yes

- block:
  - name: Unseal vault
    uri:
      url: https://{{ inventory_hostname }}.node.consul:8200/v1/sys/unseal
      method: PUT
      validate_certs: no
      body_format: json
      body:
        key: "{{ item }}"
    register: unseal
    no_log: yes
    with_items:
      - "{{ vault_init_data['keys'] | shuffle }}"
    when: unseal is not defined or unseal.json.sealed

  - name: Check vault sealed status
    uri:
      url: https://{{ inventory_hostname }}.node.consul:8200/v1/sys/seal-status
      validate_certs: no
    register: seal_status
    failed_when: seal_status.json.sealed
  when: seal_status.json.sealed
