---

cluster_name: eos
domain: eos
consul_domain: "{{ domain }}"
node_consul: "{{ inventory_hostname_short }}.node.{{ consul_domain }}"
consul_service_consul: consul.service.{{ consul_domain }}
vault_service_consul: vault.service.{{ consul_domain }}
debug: yes

dns_resolvers:
  - 8.8.8.8
  - 8.8.4.4

ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org

system_packages:
#  - nc
  - tar
#  - wget
  - git
#  - docker-python
#  - epel-release
#  - vim
#  - tree
  - ntp
  - net-tools
  - bind-utils
  - xz
  - unzip
  - curl
  - ipset
#  - sysstat