---

ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org

system_packages:
#  - nc
  - tar
#  - wget
  - git
#  - docker-python
#  - epel-release
#  - vim
#  - tree
  - ntp
#  - net-tools
  - bind-utils
  - xz
  - unzip
  - curl
  - ipset
#  - sysstat