---

- name: Update CA certificates
  command: update-ca-trust extract

- name: Start consul service
  systemd:
    name: consul
    state: restarted
    enabled: yes
    daemon-reload: yes
  listen: Start consul service

- name: Wait for consul leader election
  uri:
    url: http://{{ ansible_host }}:8500/v1/status/leader
  register: result
  until: result.status == 200 and result.json
  retries: 10
  run_once: true
  listen: Start consul service

- name: Start vault service
  systemd:
    name: vault
    state: restarted
    enabled: yes
    daemon-reload: yes
