---

- hosts: all
  become: yes
  vars:
    consul_domain: kms
  tasks:
    - include_role:
        name: consul
      tags: ['consul']

    - include_role:
        name: vault
      tags: ['vault']

    - include_role:
        name: consul
        tasks_from: tls
      when: consul_schema != 'https'
      tags: ['tls']
