---

- block:
  - name: Create consul group
    group: name=consul system=yes

  - name: Create consul user
    user:
      name=consul
      group=consul
      system=yes

  - name: Create consul directory
    file:
      path: "{{ item }}"
      state: directory
      owner: consul
      group: consul
      mode: 0755
    with_items:
      - "{{ consul_home }}"
      - "{{ consul_home }}/bin"
      - "{{ consul_home }}/data"
      - "{{ consul_config_dir }}"

  - name: Check consul package
    local_action:
      stat
        path=install/files/consul_{{ consul_version }}_linux_amd64.zip
    become: no
    register: consul_package

  - name: Download consul package locally
    local_action:
      get_url
        url=https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
        dest=install/files
        force=no
    become: no
    run_once: yes
    when: not consul_package.stat.exists

  - package: name=unzip state=present

  - name: Copy consul package to hosts
    unarchive:
      src=install/files/consul_{{ consul_version }}_linux_amd64.zip
      dest={{ consul_home }}/bin
    notify:
      - Start consul service

  - name: Copy consul config file
    template:
      src={{ item.src }}
      dest={{ item.dest }}
      owner=consul
      group=consul
      mode={{ item.mode }}
    with_items:
      - { src: "consul.json.j2", dest: "{{ consul_config_file }}", mode: "0600" }
      - { src: "consul.systemd.j2", dest: "/etc/systemd/system/consul.service", mode: "0644" }
    notify:
      - Start consul service

  - name: Set consul env variables
    template:
      src=templates/consul.sh.j2
      dest=/etc/profile.d/consul.sh
      owner=consul
      group=consul

- always:
  - meta: flush_handlers

- name: Agent ACL updated
  uri:
    url: http://{{ ansible_host }}:8500/v1/acl/update
    method: PUT
    headers:
      X-Consul-Token: "{{ consul_acl_master_token }}"
    body_format: json
    body:
      Id: "{{ consul_acl_agent_token }}"
      Name: Agent token
      Type: client
      Rules: "node \"\" { policy = \"write\" } service \"\" { policy = \"read\" }"
  run_once: true

- name: Anonymous ACL updated
  uri:
    url: http://{{ ansible_host }}:8500/v1/acl/update
    method: PUT
    headers:
      X-Consul-Token: "{{ consul_acl_master_token }}"
    body_format: json
    body:
      Id: anonymous
      Name: Anonymous Token
      Type: client
      Rules: "node \"\" { policy = \"read\" } service \"\" { policy = \"read\" }"
  run_once: true
