---

- name: Ensure vault is started
  systemd:
    name: vault
    state: started

- name: Set http schema
  set_fact:
    schema: "{{ vault_tls_enabled | default(false) | ternary('https', 'http') }}"

- name: Check vault init status
  uri:
    url: "{{ schema }}://{{ inventory_hostname }}.node.consul:8200/v1/sys/init"
    status_code: 200, 429, 500, 501, 503
  register: init_status
  until: init_status.status == 200 and init_status.json
  retries: 5
  run_once: true

- block:
  - name: Init vault
    uri:
      url: "{{ schema }}://{{ inventory_hostname }}.node.consul:8200/v1/sys/init"
      method: PUT
      body_format: json
      body:
        secret_shares: 5
        secret_threshold: 3
    register: init_response
    no_log: yes
    run_once: true

  - name: Save vault init data
    local_action:
      copy
        content={{ init_response.json }}
        dest=./vault_init_data
    become: no
    run_once: yes

  when: not init_status.json.initialized

- name: Check vault sealed status
  uri:
    url: "{{ schema }}://{{ inventory_hostname }}.node.consul:8200/v1/sys/seal-status"
  register: seal_status
  when: init_status.json.initialized

- name: Lookup vault init data
  set_fact:
    vault_init_data: "{{ lookup('file', 'vault_init_data') }}"
  no_log: yes

- block:
  - set_fact:
      unseal: false

  - name: Unseal vault
    uri:
      url: "{{ schema }}://{{ inventory_hostname }}.node.consul:8200/v1/sys/unseal"
      method: PUT
      body_format: json
      body:
        key: "{{ item }}"
    register: unseal
    no_log: yes
    with_items:
      - "{{ vault_init_data['keys'] | shuffle }}"
    when: not unseal or unseal.json.sealed

  - name: Check vault sealed status
    uri:
      url: "{{ schema }}://{{ inventory_hostname }}.node.consul:8200/v1/sys/seal-status"
    register: seal_status
    failed_when: seal_status.json.sealed

  when: not init_status.json.initialized or seal_status.json.sealed

- name: Wait for vault leader election
  uri:
    url: "{{ schema }}://vault.service.consul:8200/v1/sys/leader"
  register: vault_leader
  until: vault_leader.status == 200 and vault_leader.json.leader_address
  retries: 10
  run_once: true
