---

- name: Check ansible version
  run_once: true
  delegate_to: localhost
  assert:
    that:
      - ansible_version.full is version_compare('2.5.0.0', '>')
    msg: "Please install at least ansible 2.5.x.x in your host"

- name: Install prerequisites
  yum: name={{ item }} state=latest
  with_items:
    - "{{ system_packages }}"

#- name: Install CentOS EPEL prerequisites
#  yum: name={{ item }} state=latest
#  with_items:
#    - "{{ system_epel_packages }}"

- name: Disabling SELinux (anti-pattern)
  selinux:
    policy: targeted
    state: permissive

#- name: Effective disabling of SELinux (avoiting reboot)
#  command: /usr/sbin/setenforce 0

- name: Adding group nogroup (similar to nobody)
  group:
    name: nogroup
    state: present

- name: Disable firewalld service
  service: name=firewalld state=stopped enabled=no

#- name: Effective disabling of iptables rules
#  command: /usr/sbin/iptables -F

- name: Disable chronyd service
  service: name=chronyd state=stopped enabled=no

#- name: Passwordless pre-step PasswordAuthentication enabling
#  lineinfile:
#    dest: /etc/ssh/sshd_config
#    backup: yes
#    regexp: '^PasswordAuthentication'
#    line: 'PasswordAuthentication yes'
#
#- name: Restarting SSH daemon
#  service: name=sshd state=restarted
#
#- name: Configure /etc/host files
#  template: src=hosts.j2 dest=/etc/hosts

- name: Configure ntp servers
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: Restart ntpd service

- name: Enable ntpd service
  service: name=ntpd state=started enabled=yes
